-- create, primary key, references 예제

CREATE TABLE BOOK(
    
    BOOKID NUMBER(2) PRIMARY KEY,
    BOOKNAME VARCHAR2(40),
    PUBLISHER VARCHAR2(40),
    PRICE NUMBER(8)

);

CREATE TABLE CUSTOMER(
    
    CUSTID NUMBER(2) PRIMARY KEY,
    BOOKNAME VARCHAR2(40),
    ADDRESS VARCHAR2(50),
    PHONE VARCHAR2(20)

);

CREATE TABLE ORDERS(
    
    ORDERID NUMBER(2) PRIMARY KEY,
    CUSTID NUMBER(2) REFERENCES CUSTOMER(CUSTID),
    BOOKID NUMBER(2) REFERENCES BOOK(BOOKID),
    SALEPRICE NUMBER(8),
    ORDERDATE DATE

);

