/**
Department 테이블 생성
***/
CREATE TABLE DEPARTMENT (
    DEPT_ID   VARCHAR2(10)
        CONSTRAINT DEPARTMENT_PK PRIMARY KEY,
    DEPT_NAME VARCHAR2(25),
    DEPT_TEL  VARCHAR2(12)
);

/**
Student 테이블 생성
***/
CREATE TABLE STUDENT (
    DEPT_ID    VARCHAR2(10),
    YEAR       VARCHAR2(1),
    STUDENT_ID VARCHAR2(7),
    NAME       VARCHAR2(10) NOT NULL,
    ID_NUMBER  VARCHAR2(14) NOT NULL
        CONSTRAINT STUDENT_UK UNIQUE,
    ADDRESS    VARCHAR2(40),
    TELEPHONE  VARCHAR2(13),
    EMAIL      VARCHAR2(20),
    STATUS     VARCHAR2(1),
    I_DATE     DATE,
    CONSTRAINT STUDENT_PK PRIMARY KEY ( STUDENT_ID ),
    CONSTRAINT STUDENT_FK FOREIGN KEY ( DEPT_ID )
        REFERENCES DEPARTMENT
);

/**
Professor 테이블 생성
***/
CREATE TABLE PROFESSOR (
    PROFESSOR_ID VARCHAR2(3),
    NAME         VARCHAR2(10) NOT NULL,
    POSITION     VARCHAR2(10) NOT NULL
        CONSTRAINT PROFESSOR_CK CHECK ( POSITION IN ( '총장', '교수', '부교수', '조교수', '초빙교수' ) ),
    DEPT_ID      VARCHAR2(10),
    TELEPHONE    VARCHAR2(12)
        CONSTRAINT PROFESSOR_UK UNIQUE,
    EMAIL        VARCHAR2(20),
    DUTY         VARCHAR2(10),
    MGR          VARCHAR2(3),
    CONSTRAINT PROFESSOR_PK PRIMARY KEY ( PROFESSOR_ID ),
    CONSTRAINT PROFESSOR_FK FOREIGN KEY ( DEPT_ID )
        REFERENCES DEPARTMENT
);

alter table PROFESSOR modify(POSITION  VARCHAR2(40));

/**
Course 테이블 생성
***/
CREATE TABLE COURSE (
    COURSE_ID    VARCHAR2(5),
    TITLE        VARCHAR2(20) NOT NULL,
    C_NUMBER     NUMBER(1) NOT NULL,
    PROFESSOR_ID VARCHAR2(3),
    COURSE_FEES  NUMBER(7),
    CONSTRAINT COURSE_PK PRIMARY KEY ( COURSE_ID ),
    CONSTRAINT COURSE_FK FOREIGN KEY ( PROFESSOR_ID )
        REFERENCES PROFESSOR
);

alter table COURSE modify(TITLE  VARCHAR2(40));


/**
SG_Scores 테이블 생성
***/
CREATE TABLE SG_SCORES (
    STUDENT_ID     VARCHAR2(7),
    COURSE_ID      VARCHAR2(5),
    SCORE          NUMBER(3),
    GRADE          VARCHAR2(2),
    SCORE_ASSIGNED DATE DEFAULT SYSDATE,
    CONSTRAINT SG_SCORES_PK PRIMARY KEY ( STUDENT_ID,
                                          COURSE_ID ),
    CONSTRAINT SG_SCORES_FK1 FOREIGN KEY ( STUDENT_ID )
        REFERENCES STUDENT,
    CONSTRAINT SG_SCORES_FK2 FOREIGN KEY ( COURSE_ID )
        REFERENCES COURSE
);

/**
Score_Grade 테이블 생성
***/
CREATE TABLE SCORE_GRADE (
    LOW   NUMBER(3),
    HIGH  NUMBER(3),
    GRADE CHAR(2)
);

/**
T_Course 테이블 생성
**/
CREATE TABLE T_COURSE 
AS 
   SELECT *
   FROM  COURSE;

ALTER TABLE T_COURSE modify(TITLE  VARCHAR2(40));
  
/**
T_SG_Scores 테이블 생성
**/
CREATE TABLE T_SG_SCORES
AS
   SELECT *
FROM
    SG_SCORES;